name = "Elmfire"
uuid = "d2b3179f-ea35-45b6-b9e1-83e946046b97"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
LocalCoverage = "5f6e1e16-694c-5876-87ef-16b5274f298e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[extensions]
ElmfireKAExt = ["KernelAbstractions", "Adapt"]

[compat]
Adapt = "4"
ArchGDAL = "0.10.11"
Distributions = "0.25.123"
GeoInterface = "1.6.0"
GeoJSON = "0.8.4"
KernelAbstractions = "0.9"
LocalCoverage = "0.8.5"
Plots = "1.41.4"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Rasters = "0.14.7"
julia = "1.10.10"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "KernelAbstractions", "Adapt"]
