[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Elmfire = "d2b3179f-ea35-45b6-b9e1-83e946046b97"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Landfire = "16f38fd6-0379-4569-89bb-2d3d56e50de8"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RapidRefreshData = "6311d174-80ed-4991-8be9-d0557cea290a"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
